/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qsolutions.view;

/**
 * Check boxes for FilterView
 * @author Chris
 */
public class CheckBoxView extends javax.swing.JPanel
{
    /**
     * Creates new form CheckBoxView with the text matching label
     * @param label the text to be set for the checkBox's text
     */
    public CheckBoxView(String label)
    {
        initComponents();
        checkBox.setText(label);
        
    }

    /**
     * Returns the check box's text
     * @return the String of the text for the check box
     */
    public String getText()
    {
        return checkBox.getText();
    }
    
    /**
     * Returns a boolean for the checkBox's selection status
     * @return true if checkBox is selected, otherwise false
     */
    public boolean isSelected()
    {
        return checkBox.isSelected();
    }
    
    /**
     * Select/unselect and item
     * @param select whether to select or unselect the checkbox
     */
    public void setSelected(boolean select)
    {
        checkBox.setSelected(select);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBox = new javax.swing.JCheckBox();

        checkBox.setText(org.openide.util.NbBundle.getMessage(CheckBoxView.class, "CheckBoxView.checkBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(checkBox)
                .addGap(0, 125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(checkBox)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox;
    // End of variables declaration//GEN-END:variables
}
