/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qsolutions.view;

import org.openide.util.Lookup;
import qsolutions.api.DividerApi;
import qsolutions.api.DocumentItemApi;

/**
 * Panel for adding and editing Dividers to the exam, subclass of DesignItemView
 *
 * @author Jake
 */
public class DividerView extends DesignItemView
{
    /**
     * Creates new form PageBreakDesignPanel
     */
    public DividerView()
    {
        super();
        item = Lookup.getDefault().lookup(DividerApi.class).newItem();
        setEditView(false);
        initComponents();
        addDocumentItem.addFocusListener(this);
        
    }
    
    /**
     * Initializes the diver view
     * @param nItem item to be defaulted to
     */
    public DividerView(DividerApi nItem) 
    {
        super();
        item = nItem;
        setEditView(true);
        initComponents();
        addDocumentItem.setText(kBundle.getString("UPDATE DIVIDER"));
        addDocumentItem.addFocusListener(this);
    }

    /**
     * Fills the gui from inItem, sets isEditView to true
     *
     * @param inItem the item to load information from
     */
    protected void fillFields(DocumentItemApi inItem)
    {
        //no fields
        examNavigatorPanel.refreshView(isEditView());
    }
    
    /**
     * Add the GUI's item to the exam
     */
    public void addItem()
    {
        super.addItem();
        fillFields();
    }
    
    /**
     * Loads a new Divider when extracting
     *
     * @return a new Divider
     */
    @Override
    protected DocumentItemApi extractItem()
    {
        return Lookup.getDefault().lookup(DividerApi.class).newItem();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDocumentItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        examNavigatorPanel = new ExamNavigatorPanel(this);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("qsolutions/view/Bundle"); // NOI18N
        addDocumentItem.setText(bundle.getString("ADD DIVIDER")); // NOI18N
        addDocumentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDocumentItemActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("ADD A DIVIDER WITH THE BUTTON BELOW.")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(addDocumentItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(examNavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(examNavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(addDocumentItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDocumentItemActionPerformed( java.awt.event.ActionEvent evt )//GEN-FIRST:event_addDocumentItemActionPerformed
    {//GEN-HEADEREND:event_addDocumentItemActionPerformed
        addItem();
    }//GEN-LAST:event_addDocumentItemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDocumentItem;
    private qsolutions.view.ExamNavigatorPanel examNavigatorPanel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
