/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qsolutions.view;

import java.io.File;
import java.util.Date;
import javax.swing.JDialog;
import org.openide.util.Lookup;
import qsolutions.api.*;
import qsolutions.exam.*;

/**
 * Contains the exam summary / statistics for the contents of this exam.
 * @author Chris
 */
public class ExamSummaryView extends javax.swing.JPanel
{
    private JDialog parent;
    
    /**
     * Creates new form ExamSummaryView
     * @param nParent Parent window to exam summary
     */
    public ExamSummaryView(JDialog nParent)
    {
        initComponents();
        parent = nParent;
        Long date;
        ExamApi exam = Lookup.getDefault().lookup(ExamApi.class);
        File examFile;
        String lastModifiedString;
        // If the exam is a new file
        if (exam.getPath() == null)
        {
            lastModifiedString = "New exam";
        }
        else
        {
            lastModifiedString = (new Date((new File(exam.getPath()))
                    .lastModified())).toString();
        }
        
        lastModified.setText(lastModifiedString);
        examName.setText(exam.getTitleGroup().getTitle());
        totalMarks.setText(exam.getTotalMarks() + "");
        fillInTheBlank.setText(exam.getNumType((FillInTheBlankApi)new 
                FillInTheBlank()) + "");
        freeResponse.setText(exam.getNumType((FreeResponseApi)new 
                FreeResponse()) + "");
        matching.setText(exam.getNumType((MatchingApi)new 
                Matching()) + "");
        multipleChoice.setText(exam.getNumType((MultipleChoiceApi)new 
                MultipleChoice()) + "");
        order.setText(exam.getNumType((OrderApi)new 
                Order()) + "");
        trueFalse.setText(exam.getNumType((TrueFalseApi)new 
                TrueFalse()) + "");
        total.setText(exam.getNumQuestions() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //GEN-BEGIN
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        totalMarks = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fillInTheBlank = new javax.swing.JLabel();
        freeResponse = new javax.swing.JLabel();
        matching = new javax.swing.JLabel();
        multipleChoice = new javax.swing.JLabel();
        order = new javax.swing.JLabel();
        trueFalse = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        examName = new javax.swing.JLabel();
        lastModified = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel4.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel6.text")); // NOI18N

        totalMarks.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.totalMarks.text")); // NOI18N

        jLabel7.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel7.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel8.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel9.text")); // NOI18N

        fillInTheBlank.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.fillInTheBlank.text")); // NOI18N

        freeResponse.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.freeResponse.text")); // NOI18N

        matching.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.matching.text")); // NOI18N

        multipleChoice.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.multipleChoice.text")); // NOI18N

        order.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.order.text")); // NOI18N

        trueFalse.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.trueFalse.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel10.text")); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel11.text")); // NOI18N

        examName.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.examName.text")); // NOI18N

        lastModified.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.lastModified.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.jLabel12.text")); // NOI18N

        total.setText(org.openide.util.NbBundle.getMessage(ExamSummaryView.class, "ExamSummaryView.total.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastModified))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(examName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalMarks))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(matching))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(order))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fillInTheBlank))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(freeResponse))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(multipleChoice))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(trueFalse))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(total))))
                                    .addComponent(jLabel7))))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(examName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lastModified))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalMarks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fillInTheBlank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(freeResponse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(matching))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(multipleChoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(order))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(trueFalse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //GEN-END
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        parent.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel examName;
    private javax.swing.JLabel fillInTheBlank;
    private javax.swing.JLabel freeResponse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastModified;
    private javax.swing.JLabel matching;
    private javax.swing.JLabel multipleChoice;
    private javax.swing.JLabel order;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalMarks;
    private javax.swing.JLabel trueFalse;
    // End of variables declaration//GEN-END:variables
}
