package qsolutions.view;

import java.util.Set;
import org.openide.util.Lookup;
import org.openide.windows.WindowManager;
import qsolutions.api.DocumentItemApi;
import qsolutions.api.ExamApi;
import qsolutions.api.PageBreakApi;
import qsolutions.gui.TableViewTopComponent;

/**
 * The view for the PageBreak question.
 * @author Jake
 */
public class PageBreakView extends DesignItemView
{
    /**
     * Creates new form PageBreakView.
     */
    public PageBreakView() 
    {
        super();
        item = Lookup.getDefault().lookup(PageBreakApi.class).newItem();
        setEditView(false);
        initComponents();
        fillFields();
        addDocumentItem.addFocusListener(this);
    }
    
    /**
     * Initializes the page break view
     * @param nItem api whos information will be extracted
     */
    public PageBreakView(PageBreakApi nItem) 
    {
        super();
        item = nItem;
        setEditView(true);
        initComponents();
        fillFields();
        addDocumentItem.setText(kBundle.getString("UPDATE PAGE BREAK"));
        addDocumentItem.addFocusListener(this);
    }
    
    /**
     * Fills the gui from inItem, sets isEditView to true
     * @param inItem the item to load information from
     */
    protected void fillFields( DocumentItemApi inItem ) 
    {
        //no fields
        examNavigatorPanel.refreshView(isEditView());
    }
    
    /**
     * Adds the GUI's item to the exam
     */
    @Override
    public void addItem()
    {
        super.addItem();
        item = Lookup.getDefault().lookup(PageBreakApi.class);
        fillFields();
    }
    
    /**
     * Extracts the item from the GUI
     * @return a new PageBreak
     */
    @Override
    protected DocumentItemApi extractItem() 
    {
        return Lookup.getDefault().lookup(PageBreakApi.class).newItem();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDocumentItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        examNavigatorPanel = new ExamNavigatorPanel(this);

        addDocumentItem.setText(org.openide.util.NbBundle.getMessage(PageBreakView.class, "PageBreakView.addDocumentItem.text")); // NOI18N
        addDocumentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDocumentItemActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PageBreakView.class, "PageBreakView.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(examNavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(addDocumentItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(examNavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(addDocumentItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * when the add button is pressed store the item appropriately
     * @param evt unused
     */
    private void addDocumentItemActionPerformed( java.awt.event.ActionEvent evt )//GEN-FIRST:event_addDocumentItemActionPerformed
    {//GEN-HEADEREND:event_addDocumentItemActionPerformed
        addItem();
    }//GEN-LAST:event_addDocumentItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDocumentItem;
    private qsolutions.view.ExamNavigatorPanel examNavigatorPanel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
