/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qsolutions.view;

import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.openide.windows.WindowManager;
import qsolutions.gui.TableViewTopComponent;

/**
 * Panel displaying options for different forms of randomization
 */
public class RandomizeView extends javax.swing.JPanel
{
    private static final String kBundleName = "qsolutions/view/Bundle";
    private static final String kRandomizePropmt = 
            "RANDOMIZE ALL AND RANDOMIZE SELECTED CANNOT BOTH BE SELECTED," +
            " PLEASE CHOOSE ONE";
    private static final ResourceBundle kBundle =
            ResourceBundle.getBundle(kBundleName);
    
    private JDialog parent;
    /**
     * Creates new form RandomizeView
     * @param nParent the dialog box containing this view
     */
    public RandomizeView(JDialog nParent)
    {
        initComponents();
        parent = nParent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //GEN-BEGIN
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        randomizeGroup = new javax.swing.ButtonGroup();
        randomizeMC = new javax.swing.JCheckBox();
        randomizeMatching = new javax.swing.JCheckBox();
        randomizeOrder = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        randomize = new javax.swing.JButton();
        randomizeSelected = new javax.swing.JCheckBox();
        randomizeAll = new javax.swing.JCheckBox();

        randomizeMC.setText(org.openide.util.NbBundle.getMessage(RandomizeView.class, "RandomizeView.randomizeMC.text")); // NOI18N

        randomizeMatching.setText(org.openide.util.NbBundle.getMessage(RandomizeView.class, "RandomizeView.randomizeMatching.text")); // NOI18N
        randomizeMatching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomizeMatchingActionPerformed(evt);
            }
        });

        randomizeOrder.setText(org.openide.util.NbBundle.getMessage(RandomizeView.class, "RandomizeView.randomizeOrder.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(RandomizeView.class, "RandomizeView.jLabel1.text")); // NOI18N

        cancel.setText(org.openide.util.NbBundle.getMessage(RandomizeView.class, "RandomizeView.cancel.text")); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        randomize.setText(org.openide.util.NbBundle.getMessage(RandomizeView.class, "RandomizeView.randomize.text")); // NOI18N
        randomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomizeActionPerformed(evt);
            }
        });

        randomizeSelected.setText(org.openide.util.NbBundle.getMessage(RandomizeView.class, "RandomizeView.randomizeSelected.text")); // NOI18N

        randomizeAll.setText(org.openide.util.NbBundle.getMessage(RandomizeView.class, "RandomizeView.randomizeAll.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(randomizeMC)
                            .addComponent(randomizeMatching)
                            .addComponent(randomizeOrder))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(randomize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(randomizeAll)
                            .addComponent(randomizeSelected))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(randomizeAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomizeSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomizeMC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomizeMatching)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomizeOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(randomize))
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //GEN-END
    private void cancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelActionPerformed
    {//GEN-HEADEREND:event_cancelActionPerformed
        parent.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void randomizeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_randomizeActionPerformed
    {//GEN-HEADEREND:event_randomizeActionPerformed
        boolean randomAll, randomSelected, randomMC, randomOrd, randomMat;
        randomAll = randomizeAll.isSelected();
        randomSelected = randomizeSelected.isSelected();
        randomMC = randomizeMC.isSelected();
        randomOrd = randomizeOrder.isSelected();
        randomMat = randomizeMatching.isSelected();
        TableViewTopComponent table =
                    (TableViewTopComponent) 
                    WindowManager.getDefault().findTopComponent(
                    "TableViewTopComponent");
        // If both Randomize All and Randomize Selected were checked
        if ( randomAll && randomSelected )
        {
            JOptionPane.showMessageDialog(null, 
                    kBundle.getString(kRandomizePropmt));
        }
        table.randomize(randomAll, randomSelected, randomMC, randomOrd, 
                randomMat);
        parent.dispose();
    }//GEN-LAST:event_randomizeActionPerformed

    private void randomizeMatchingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_randomizeMatchingActionPerformed
    {//GEN-HEADEREND:event_randomizeMatchingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randomizeMatchingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton randomize;
    private javax.swing.JCheckBox randomizeAll;
    private javax.swing.ButtonGroup randomizeGroup;
    private javax.swing.JCheckBox randomizeMC;
    private javax.swing.JCheckBox randomizeMatching;
    private javax.swing.JCheckBox randomizeOrder;
    private javax.swing.JCheckBox randomizeSelected;
    // End of variables declaration//GEN-END:variables
}
